name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v8
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          sudo apt-get update
          sudo apt-get install -y eapoltest pipx
          pipx ensurepath
          sudo pipx ensurepath --global
      - run: go build -v ./...
      - run: make test
      - uses: codecov/codecov-action@v5
        with:
          use_oidc: true
